$aaa = [
    {
        "id": 182,
        "edit_history": "",
        "commentable_id": 1,
        "commentable_type": "Story",
        "user_id": 1,
        "reply": false,
        "comment_number": 143,
        "body": "a",
        "date": "less than a minute",
        "author_nick": "Aleksandr",
        "author_avatar": "https://weedblogimages.s3.amazonaws.com/q7vsjwskn34hqxgtmppk9zudn5w7",
        "created_at": "2021-06-24T21:28:19.365Z",
        "updated_at": "2021-06-24T21:28:19.365Z",
        "original_comment_author": "null",
        "comments": [
            {
                "id": 185,
                "edit_history": "",
                "commentable_id": 182,
                "commentable_type": "Comment",
                "user_id": 1,
                "reply": true,
                "comment_number": 146,
                "body": "aa",
                "date": "less than a minute",
                "author_nick": "Aleksandr",
                "author_avatar": "https://weedblogimages.s3.amazonaws.com/q7vsjwskn34hqxgtmppk9zudn5w7",
                "created_at": "2021-06-24T21:41:03.739Z",
                "updated_at": "2021-06-24T21:41:03.739Z",
                "original_comment_author": "Aleksandr",
                "comments": []
            },
            {
                "id": 186,
                "edit_history": "",
                "commentable_id": 182,
                "commentable_type": "Comment",
                "user_id": 1,
                "reply": true,
                "comment_number": 147,
                "body": "aaa",
                "date": "less than a minute",
                "created_at": "2021-06-24T21:41:13.310Z",
                "updated_at": "2021-06-24T21:41:13.310Z",
                "original_comment_author": "Aleksandr",
                "comments": []
            },
            {
                "id": 187,
                "edit_history": "",
                "commentable_id": 182,
                "commentable_type": "Comment",
                "user_id": 1,
                "reply": true,
                "comment_number": 148,
                "body": "aaaa",
                "date": "less than a minute",
                "author_nick": "Aleksandr",
                "author_avatar": "https://weedblogimages.s3.amazonaws.com/q7vsjwskn34hqxgtmppk9zudn5w7",
                "created_at": "2021-06-24T21:41:22.372Z",
                "updated_at": "2021-06-24T21:41:22.372Z",
                "original_comment_author": "Aleksandr",
                "comments": []
            }
        ]
    },
    {
        "id": 183,
        "edit_history": "",
        "commentable_id": 1,
        "commentable_type": "Story",
        "user_id": 1,
        "reply": false,
        "comment_number": 144,
        "body": "b",
        "date": "less than a minute",
        "author_nick": "Aleksandr",
        "author_avatar": "https://weedblogimages.s3.amazonaws.com/q7vsjwskn34hqxgtmppk9zudn5w7",
        "created_at": "2021-06-24T21:28:22.649Z",
        "updated_at": "2021-06-24T21:28:22.649Z",
        "original_comment_author": "null",
        "comments": []
    },
    {
        "id": 184,
        "edit_history": "",
        "commentable_id": 1,
        "commentable_type": "Story",
        "user_id": 1,
        "reply": false,
        "comment_number": 145,
        "body": "c",
        "date": "less than a minute",
        "author_nick": "Aleksandr",
        "author_avatar": "https://weedblogimages.s3.amazonaws.com/q7vsjwskn34hqxgtmppk9zudn5w7",
        "created_at": "2021-06-24T21:28:25.672Z",
        "updated_at": "2021-06-24T21:28:25.672Z",
        "original_comment_author": "null",
        "comments": []
    }
]        